/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadAPP;

/**
 *
 * @author perey
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMalumno = new javax.swing.JMenu();
        JMIalumno = new javax.swing.JMenuItem();
        JMmateria = new javax.swing.JMenu();
        JMImateria = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        JMIinscripciones = new javax.swing.JMenuItem();
        JMInotas = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        JMIalumxmat = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        JMalumno.setText("Alumno");

        JMIalumno.setText("Formulario de Alumno");
        JMIalumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIalumnoActionPerformed(evt);
            }
        });
        JMalumno.add(JMIalumno);

        jMenuBar1.add(JMalumno);

        JMmateria.setText("Materia");

        JMImateria.setText("Formulario de Materia");
        JMImateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMImateriaActionPerformed(evt);
            }
        });
        JMmateria.add(JMImateria);

        jMenuBar1.add(JMmateria);

        jMenu4.setText("Administracion");

        JMIinscripciones.setText("Manejo de Inscripciones");
        JMIinscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIinscripcionesActionPerformed(evt);
            }
        });
        jMenu4.add(JMIinscripciones);

        JMInotas.setText("Administracion de notas");
        JMInotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMInotasActionPerformed(evt);
            }
        });
        jMenu4.add(JMInotas);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Consultas");

        JMIalumxmat.setText("Alumnos por Materia");
        JMIalumxmat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIalumxmatActionPerformed(evt);
            }
        });
        jMenu5.add(JMIalumxmat);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMIalumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIalumnoActionPerformed
 escritorio.removeAll();
        escritorio.repaint();
        Formularioalumno gdp = new Formularioalumno();
        gdp.setVisible(true);
        escritorio.add(gdp);
        escritorio.moveToFront(gdp);
        // TODO add your handling code here:
    }//GEN-LAST:event_JMIalumnoActionPerformed

    private void JMImateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMImateriaActionPerformed
         escritorio.removeAll();
        escritorio.repaint();
        FormularioMateria gdp = new FormularioMateria();
        gdp.setVisible(true);
        escritorio.add(gdp);
        escritorio.moveToFront(gdp);
        // TODO add your handling code here:

// TODO add your handling code here:
    }//GEN-LAST:event_JMImateriaActionPerformed

    private void JMIinscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIinscripcionesActionPerformed
     escritorio.removeAll();
        escritorio.repaint();
        FormularioInscripciones gdp = new FormularioInscripciones();
        gdp.setVisible(true);
        escritorio.add(gdp);
        escritorio.moveToFront(gdp);  
        
// TODO add your handling code here:
    }//GEN-LAST:event_JMIinscripcionesActionPerformed

    private void JMInotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMInotasActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        CargadeNotas gdp = new CargadeNotas ();
        gdp.setVisible(true);
        escritorio.add(gdp);
        escritorio.moveToFront(gdp);  
        
// TODO add your handling code here:
    }//GEN-LAST:event_JMInotasActionPerformed

    private void JMIalumxmatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIalumxmatActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
       AlumnosporMateria gdp = new AlumnosporMateria ();
        gdp.setVisible(true);
        escritorio.add(gdp);
        escritorio.moveToFront(gdp);  
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_JMIalumxmatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMIalumno;
    private javax.swing.JMenuItem JMIalumxmat;
    private javax.swing.JMenuItem JMIinscripciones;
    private javax.swing.JMenuItem JMImateria;
    private javax.swing.JMenuItem JMInotas;
    private javax.swing.JMenu JMalumno;
    private javax.swing.JMenu JMmateria;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
